#! /usr/bin/env bash
<<DOC
convert from bam to bw, gzipping all intermediary steps.
DOC

set -o nounset -o pipefail -o errexit

function usage () {
    echo "Check your args. This script submits to the normal queue.
         "
    echo "Usage: sh $0 <BAM> <CHROMOSOME_SIZES>"
    echo "Example: sh $0 MP1.bam ~/reference/hg19/hg19.sizes"
    exit 1
}

if [ $# -lt 2 ]; then
    usage
fi

bam=$1
chromsizes=$2
sample=${bam/.bam}
runscript="bamtobw.sh"

cat <<runscript >${runscript}
#BSUB -J bamtobw
#BSUB -e bamtobw.%J.err
#BSUB -o bamtobw.%J.out

bedtools bamtobed -i $sample.bam > $sample.bed
awk '\$6=="+"' $sample.bed > $sample.pos.bed
awk '\$6=="-"' $sample.bed > $sample.neg.bed
bedSort $sample.pos.bed $sample.pos.bed
bedSort $sample.neg.bed $sample.neg.bed
bedtools genomecov -strand + -bg -ibam $bam -g $chromsizes > $sample.pos.bedgraph
bedtools genomecov -strand - -bg -ibam $bam -g $chromsizes > $sample.neg.bedgraph
bedGraphToBigWig $sample.pos.bedgraph $chromsizes $sample.pos.bw
bedGraphToBigWig $sample.neg.bedgraph $chromsizes $sample.neg.bw
gzip -f $sample.*.bed $sample.*.bedgraph
runscript

job=$(bsub < $runscript)
jobid=$(echo $job | sed -rn 's/.*<([0-9]+)>.*/\1/p')

mv bamtobw.sh bamtobw.$jobid.sh
echo $jobid
