#! /usr/bin/env bash
set -o nounset -o errexit

function usage () {
    echo "Run fastqc on supplied fastq. This script submits to the normal queue.
    "
    echo ">> Check your args...
    "
    echo "Usage: $(basename $0) <fastq> <out [ optional ]>"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

fastqc=/vol1/home/brownj/opt/fastqc/fastqc
fastq=$1
out=${2:-"."}
sample=${fastq%.f*}
runscript="fastqc.sh"

cat <<runscript >${runscript}
#! /usr/bin/env bash
#BSUB -J fastqc
#BSUB -e fastqc.%J.err
#BSUB -o fastqc.%J.out

$fastqc --outdir=$out $fastq
runscript

job=$(bsub < $runscript)
jobid=$(echo $job | sed -rn 's/.*<([0-9]+)>.*/\1/p')

mv fastqc.sh fastqc.$jobid.sh
echo $jobid